version: 2

sources:
  - name: homework4
    database: latest-project-410306
    tables:
      - name: full_green_taxi_data
      - name: full_yellow_taxi_data
      - name: fhv_2019_trip_data
      
models:
  - name: stg_yellow_cabb_data
    description: ""
    columns:
      - name: vendorid
        data_type: int64
        description: ""

      - name: lpep_pickup_datetime
        data_type: int64
        description: ""

      - name: lpep_dropoff_datetime
        data_type: int64
        description: ""

      - name: store_and_fwd_flag
        data_type: string
        description: ""

      - name: ratecodeid
        data_type: float64
        description: ""

      - name: pulocationid
        data_type: float64
        description: ""

      - name: dolocationid
        data_type: float64
        description: ""

      - name: passenger_count
        data_type: float64
        description: ""

      - name: trip_distance
        data_type: float64
        description: ""

      - name: fare_amount
        data_type: float64
        description: ""

      - name: extra
        data_type: float64
        description: ""

      - name: mta_tax
        data_type: float64
        description: ""

      - name: tip_amount
        data_type: float64
        description: ""

      - name: tolls_amount
        data_type: float64
        description: ""

      - name: ehail_fee
        data_type: float64
        description: ""

      - name: improvement_surcharge
        data_type: float64
        description: ""

      - name: total_amount
        data_type: float64
        description: ""

      - name: payment_type
        data_type: float64
        description: ""

      - name: trip_type
        data_type: float64
        description: ""

      - name: congestion_surcharge
        data_type: float64
        description: ""

  - name: stg_grren_taxi_trip_2020
    description: ""
    columns:
      - name: tripid
        data_type: string
        description: ""

      - name: vendorid
        data_type: int64
        description: ""

      - name: ratecodeid
        data_type: int64
        description: ""

      - name: pickup_locationid
        data_type: int64
        description: ""

      - name: dropoff_locationid
        data_type: int64
        description: ""

      - name: store_and_fwd_flag
        data_type: string
        description: ""

      - name: passenger_count
        data_type: int64
        description: ""

      - name: trip_distance
        data_type: numeric
        description: ""

      - name: trip_type
        data_type: int64
        description: ""

      - name: fare_amount
        data_type: numeric
        description: ""

      - name: extra
        data_type: numeric
        description: ""

      - name: mta_tax
        data_type: numeric
        description: ""

      - name: tip_amount
        data_type: numeric
        description: ""

      - name: tolls_amount
        data_type: numeric
        description: ""

      - name: ehail_fee
        data_type: numeric
        description: ""

      - name: improvement_surcharge
        data_type: numeric
        description: ""

      - name: total_amount
        data_type: numeric
        description: ""

      - name: payment_type
        data_type: int64
        description: ""

      - name: payment_type_description
        data_type: string
        description: ""
