version: 2

sources:
  - name: data_talk_final_project

    database: latest-project-410306
    tables:
      - name: data_talk_final_project_table
     
      
models:
  - name: stg_data_talk_final_project_table
    description: ""
    columns:
      - name: exchangeId
        data_type: string
        description: ""

      - name: rank
        data_type: int64
        description: ""

      - name: baseSymbol
        data_type: string
        description: ""

      - name: baseId
        data_type: string
        description: ""

      - name: quoteSymbol
        data_type: string
        description: ""

      - name: quoteId
        data_type: string
        description: ""

      - name: priceQuote
        data_type: float64
        description: ""

      - name: priceUsd
        data_type: float64
        description: ""

      - name: volumeUsd24Hr
        data_type: float64
        description: ""

      - name: percentExchangeVolume
        data_type: float64
        description: ""

      - name: tradesCount24Hr
        data_type: int64
        description: ""

      - name: updated	
        data_type: int64
        description: ""
